kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.database.config.name }}
data:
  POSTGRES_DB: {{ .Values.database.config.data.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.database.config.data.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.database.config.data.POSTGRES_PASSWORD | quote }}
