kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.backend.config.name }}
data:
  DB_SERVER: jdbc:postgresql://postgresql:5432/{{ .Values.database.config.data.POSTGRES_DB }}?useSSL=false
  DB_USERNAME: {{ .Values.database.config.data.POSTGRES_USER }}
  DB_PASSWORD: {{ .Values.database.config.data.POSTGRES_PASSWORD | quote}}

