apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.appName }}
  labels:
    app: {{ .Values.backend.appName }}
    tier: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.appName }}
      tier: {{ .Values.backend.service.spec.selector.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.appName }}
        tier: {{ .Values.backend.service.spec.selector.tier }}
    spec: # Pod spec
      containers:
        - name: {{ .Values.backend.containerName }}
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag}}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.backend.config.name }}